language: python
sudo: required
dist: xenial
python:
  - '3.7'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
script: 'pipenv run nosetests --cover-xml-file=coverage.xml'
after_success:
  - coveralls